import test from 'node:test'
import assert from 'node:assert/strict'
import { chromium } from 'playwright'

const base = process.env.RESUME_EDITOR_URL
const storageKey = 'resume.library.v1'

test('resume document editor browser integration: isolation, versions, images, drag, PDF and responsive drawers', { skip: !base, timeout: 90000 }, async () => {
  const origin = new URL(base).origin
  assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname))
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  await context.route('**/*', route => {
    const request = route.request()
    if (new URL(request.url()).origin !== origin || request.url().includes('/api/')) return route.abort()
    return route.continue()
  })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => dialog.accept())
  const saved = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), storageKey)
  const editField = async (button, field, value) => {
    await page.getByRole('button', { name: button, exact: true }).click()
    await page.getByRole('dialog').getByLabel(field, { exact: true }).fill(value)
    await page.getByRole('button', { name: 'Close module editor', exact: true }).click()
  }
  try {
    await page.goto(base)
    await page.getByLabel('Active resume').waitFor()
    const sampleId = (await saved()).activeDocumentId
    await page.screenshot({ path: '/tmp/resume-editor-sample.png' })
    await page.getByRole('button', { name: 'Blank', exact: true }).click()
    await page.waitForFunction(key => JSON.parse(localStorage.getItem(key)).documents.length === 2, storageKey)
    const blankId = (await saved()).activeDocumentId
    assert.notEqual(blankId, sampleId)
    assert.equal(await page.getByRole('region', { name: 'Resume library', exact: true }).count(), 1)
    assert.equal(await page.locator('img[src*="Avatar"], img[src*="banner"], img[src*="project-"]').count(), 0)
    assert.doesNotMatch(await page.locator('.resume-profile').innerText(), /Xiaolei|Bayer|Guangzhou/)
    await page.getByLabel('Document name', { exact: true }).fill('Landscape portfolio')
    await page.getByLabel('Edit mode', { exact: true }).check()
    await editField('Edit name', 'name', 'QA Architect')
    await editField('Edit headline', 'headline', 'Landscape Architect')
    await page.getByRole('button', { name: 'Edit photo', exact: true }).click()
    await page.getByRole('dialog').getByLabel('Upload image').first().setInputFiles({ name: 'portrait.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQkAAAAASUVORK5CYII=', 'base64') })
    await page.locator('.resume-image-field img').waitFor()
    await page.getByRole('button', { name: 'Close module editor', exact: true }).click()
    await editField('Edit summary 1 summary', 'summary', 'Designed public gardens.')
    await page.getByLabel('Resume theme').selectOption('nord')
    await page.getByLabel('Active resume').selectOption(sampleId)
    await page.waitForFunction(id => document.querySelector('[aria-label="Active resume"]').value === id, sampleId)
    await page.getByLabel('Active resume').selectOption(blankId)
    await page.getByRole('heading', { name: 'QA Architect' }).waitFor()
    assert.equal(await page.locator('h1').innerText(), 'QA Architect')
    assert.match(await page.locator('main').innerText(), /Designed public gardens/)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.getByText('Saved locally', { exact: true }).waitFor()
    assert.equal((await saved()).documents.find(item => item.id === blankId).resume.general.name, 'QA Architect')
    assert.match((await saved()).documents.find(item => item.id === blankId).resume.general.photo, /^data:image\/png;base64,/)
    assert.notEqual((await saved()).documents.find(item => item.id === sampleId).resume.general.name, 'QA Architect')
    await page.reload()
    await page.getByRole('heading', { name: 'QA Architect' }).waitFor()
    assert.equal(await page.getByLabel('Resume theme').inputValue(), 'nord')
    await page.getByLabel('Edit mode', { exact: true }).check()
    await page.getByRole('button', { name: 'Add Projects & Achievements entry', exact: true }).click()
    await page.getByRole('dialog').getByLabel('title', { exact: true }).fill('Public garden')
    await page.getByRole('dialog').getByLabel('image', { exact: true }).fill('/images/Avatar.jpg')
    await page.getByRole('button', { name: 'Close module editor', exact: true }).click()
    await page.getByRole('button', { name: 'Edit projects 1 image', exact: true }).click()
    await page.getByRole('button', { name: 'Clear image', exact: true }).click()
    await page.getByRole('button', { name: 'Close module editor', exact: true }).click()
    assert.equal(await page.locator('img[src*="Avatar"], img[src*="project-"]').count(), 0)
    const drag = page.getByRole('button', { name: 'Drag handle: Projects & Achievements', exact: true })
    await drag.dragTo(page.locator('[data-editable-section="summary"]'))
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.getByText('Saved locally', { exact: true }).waitFor()
    assert.equal((await saved()).documents.find(item => item.id === blankId).sectionOrder[0], 'projects')
    await page.getByText('Versions (0)', { exact: true }).click()
    await page.getByLabel('Version label', { exact: true }).fill('Milestone')
    await page.getByRole('button', { name: 'Save version', exact: true }).click()
    await page.getByText('Version saved', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Restore Milestone', exact: true }).click()
    await page.getByText('Restored as a new resume', { exact: true }).waitFor()
    assert.equal((await saved()).documents.length, 3)
    await page.evaluate(() => { window.print = () => { window.__printedTitle = document.title } })
    await page.getByRole('button', { name: 'PDF', exact: true }).click()
    assert.match(await page.evaluate(() => window.__printedTitle), /QA Architect.*Landscape portfolio/)
    await page.emulateMedia({ media: 'print' })
    assert.equal(await page.locator('.resume-library').isVisible(), false)
    assert.equal(await page.locator('.resume-editor-toolbar').isVisible(), false)
    await page.emulateMedia({ media: 'screen' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByLabel('Edit mode', { exact: true }).check()
    await page.getByRole('button', { name: 'Edit name', exact: true }).click()
    const rect = await page.getByRole('dialog').boundingBox()
    assert.ok(rect.width <= 390 && rect.x >= 0)
    await page.screenshot({ path: '/tmp/resume-editor-mobile.png' })
    await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('dialog').count(), 0)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.getByText('Versions (0)', { exact: true }).click()
    await page.getByLabel('Version label', { exact: true }).fill('Mobile milestone')
    await page.getByRole('button', { name: 'Save version', exact: true }).click()
    await page.getByText('Version saved', { exact: true }).waitFor()
    assert.ok((await saved()).versions.some(version => version.label === 'Mobile milestone'))
    // Deleting the active saved document in a different tab must select a valid fallback.
    await page.evaluate(key => {
      const state = JSON.parse(localStorage.getItem(key))
      state.documents = state.documents.filter(item => item.id !== state.activeDocumentId)
      state.activeDocumentId = state.documents[0].id
      localStorage.setItem(key, JSON.stringify(state))
      window.dispatchEvent(new Event('storage'))
    }, storageKey)
    await page.waitForFunction(id => document.querySelector('[aria-label="Active resume"]').value === id, sampleId)
    await page.getByLabel('Active resume').selectOption(blankId)
    await page.getByRole('heading', { name: 'QA Architect' }).waitFor()
    await page.getByLabel('Document name', { exact: true }).fill('Unsaved retained draft')
    await page.evaluate(key => {
      const state = JSON.parse(localStorage.getItem(key))
      state.documents = state.documents.filter(item => item.id !== state.activeDocumentId)
      state.activeDocumentId = state.documents[0].id
      localStorage.setItem(key, JSON.stringify(state))
      window.dispatchEvent(new Event('storage'))
    }, storageKey)
    await page.waitForFunction(() => document.querySelector('[aria-label="Active resume"] option:checked')?.textContent === 'Unsaved retained draft *')
    assert.equal(await page.locator('h1').innerText(), 'QA Architect')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.getByRole('alert').getByText('Resume document was deleted.').waitFor()
    assert.equal(await page.getByLabel('Document name', { exact: true }).inputValue(), 'Unsaved retained draft')
    assert.deepEqual(errors, [])
  } finally { await browser.close() }
})

test('production shows only the public sample and never loads private resumes or versions', { skip: !process.env.RESUME_PUBLIC_URL, timeout: 30000 }, async () => {
  const url = process.env.RESUME_PUBLIC_URL
  assert.ok(['localhost', '127.0.0.1'].includes(new URL(url).hostname))
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
    await page.route('**/*', route => new URL(route.request().url()).origin === new URL(url).origin ? route.continue() : route.abort())
    await page.addInitScript(key => localStorage.setItem(key, 'PRIVATE_RESUME_DO_NOT_LOAD'), storageKey)
    await page.goto(url)
    assert.equal(await page.getByLabel('Active resume').count(), 0)
    assert.equal(await page.getByLabel('Edit mode', { exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: 'Sync', exact: true }).count(), 0)
    assert.equal(await page.getByLabel('Published resume version').count(), 0)
    await page.getByRole('heading', { name: 'Xiaolei Zhu, PhD', exact: true }).waitFor()
    assert.equal(await page.locator('.resume-profile img').count(), 1)
    assert.doesNotMatch(await page.locator('main').innerText(), /PRIVATE_RESUME_DO_NOT_LOAD/)
    assert.equal(await page.evaluate(key => localStorage.getItem(key), storageKey), 'PRIVATE_RESUME_DO_NOT_LOAD')
    await page.evaluate(() => { window.print = () => { window.__printedTitle = document.title } })
    await page.getByRole('button', { name: 'PDF', exact: true }).click()
    assert.match(await page.evaluate(() => window.__printedTitle), /Xiaolei Zhu/)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  } finally { await browser.close() }
})
